final List<Map<String, dynamic>> courses = [
  {
    'imageUrl': 'https://picsum.photos/200/300',
    'tags': ['All level'],
    'title': 'Sketch from A to Z: for app designer',
    'description': 'Proposal indulged no do sociable he throwing settling.',
    'rating': 4.0,
    'duration': 13,
    'lectures': 15,
    'category': 'Web Design',
  },
  {
    'imageUrl': 'https://picsum.photos/200/300',
    'tags': ['Beginner', 'Design'],
    'title': 'UI/UX Design Masterclass',
    'description': 'Dive into the world of user-centered design.',
    'rating': 4.5,
    'duration': 20,
    'lectures': 42,
    'category': 'Web Design',
  },
  {
    'imageUrl': 'https://picsum.photos/200/300',
    'tags': ['All level'],
    'title': 'Sketch from A to Z: for app designer',
    'description': 'Proposal indulged no do sociable he throwing settling.',
    'rating': 4.0,
    'duration': 13,
    'lectures': 15,
    'category': 'Web Design',
  },
  {
    'imageUrl': 'https://picsum.photos/200/300',
    'tags': ['Beginner', 'Design'],
    'title': 'UI/UX Design Masterclass',
    'description': 'Dive into the world of user-centered design.',
    'rating': 4.5,
    'duration': 20,
    'lectures': 42,
    'category': 'development',
  },
  {
    'imageUrl': 'https://picsum.photos/200/300',
    'tags': ['All level'],
    'title': 'Sketch from A to Z: for app designer',
    'description': 'Proposal indulged no do sociable he throwing settling.',
    'rating': 4.0,
    'duration': 13,
    'lectures': 15,
    'category': 'development',
  },
  {
    'imageUrl': 'https://picsum.photos/200/300',
    'tags': ['Beginner', 'Design'],
    'title': 'UI/UX Design Masterclass',
    'description': 'Dive into the world of user-centered design.',
    'rating': 4.5,
    'duration': 20,
    'lectures': 42,
    'category': 'development',
  },
  {
    'imageUrl': 'https://picsum.photos/200/300',
    'tags': ['All level'],
    'title': 'Sketch from A to Z: for app designer',
    'description': 'Proposal indulged no do sociable he throwing settling.',
    'rating': 4.0,
    'duration': 13,
    'lectures': 15,
    'category': 'development',
  },
  {
    'imageUrl': 'https://picsum.photos/200/300',
    'tags': ['Beginner', 'Design'],
    'title': 'UI/UX Design Masterclass',
    'description': 'Dive into the world of user-centered design.',
    'rating': 4.5,
    'duration': 20,
    'lectures': 42,
    'category': 'development',
  },
];
